# vim:foldmethod=marker filetype=zsh

# CFG {{{

# Overall home
export LLZHOME="$HOME/llz"
# dir to hold dotfiles
export LLZCFG="$LLZHOME/cfg/dot"

# Dotfile src -> dst pairs
LLZDOTPAIRS=(
    $LLZCFG/vimrc         $HOME/.vim/vimrc
    $LLZCFG/nvim.vimrc    $HOME/.config/nvim/vimrc
    $LLZCFG/nvim.init.lua $HOME/.config/nvim/init.lua
    $LLZCFG/coc.json      $HOME/.vim/coc-settings.json
    $LLZCFG/coc.json      $HOME/.config/nvim/coc-settings.json
    $LLZCFG/gitconfig     $HOME/.gitconfig
    $LLZCFG/zshrc         $HOME/.zshrc
    $LLZCFG/p10k.zsh      $HOME/.p10k.zsh
    $LLZCFG/tmux.conf     $HOME/.tmux.conf
    $LLZCFG/ssh-config    $HOME/.ssh/config
    $LLZCFG/hgrc          $HOME/.hgrc
)

# Symlink a dotfile to their default location
linkfile() {
    local src="$1" dst="$2"
    mkdir -p "$(dirname "$dst")"
    if [[ -f $src && ! -f $dst ]]; then
        ln -s "$src" "$dst"
    fi
}

# Symlink all dotfile pairs
for ((i=1; i<=${#LLZDOTPAIRS[@]}; i+=2)); do
    linkfile "${LLZDOTPAIRS[$i]}" "${LLZDOTPAIRS[$((i+1))]}"
done

# Symlink Rime dotfiles
if [[ -d "$HOME/Library/Rime" ]]; then
    rimeloc="$HOME/Library/Rime"
elif [[ -d "$HOME/.config/ibus/rime/" ]]; then
    rimeloc="$HOME/.config/ibus/rime/"
elif [[ -d "$HOME/.ibus/rime/" ]]; then
    rimeloc="$HOME/.ibus/rime/"
elif [[ -d "$HOME/.local/share/fcitx5/rime/" ]]; then
    rimeloc="$HOME/.local/share/fcitx5/rime/"
else
    echo "Warning: Rime config directory not found, skipping." >&2
    rimeloc=""
fi
if [[ -n $rimeloc ]]; then
    for llzrimefile in "$LLZCFG/rime"/*; do
        linkfile "$llzrimefile" "$rimeloc/$(basename $llzrimefile)"
    done
fi

# Edit dotfiles
rc() {
    local -A files=(
        [coc]=$LLZCFG/coc.json
        [git]=$LLZCFG/gitconfig
        [hg]=$LLZCFG/hgrc
        [nv]=$LLZCFG/nvim.vimrc
        [nvim]=$LLZCFG/nvim.vimrc
        [p10k]=$LLZCFG/p10k.zsh
        [readme]=$LLZCFG/README.md
        [ssh]=$LLZCFG/sshconfig
        [tmux]=$LLZCFG/tmux.conf
        [vi]=$LLZCFG/vimrc
        [vim]=$LLZCFG/vimrc
        [zsh]=$LLZCFG/zshrc
    )
    local -A dirs=(
        ['']=$LLZCFG
        [exe]="$LLZHOME/cfg/exe"
        [rime]="$LLZCFG/rime"
    )
    if [[ $1 == -h ]]; then
        echo "Available configs: vi(m), nv(im), coc, exe, git, zsh, p10k, tmux, rime, readme, ssh"
    elif [[ -n ${files[$1]+_} ]]; then
        $EDITOR ${files[$1]}
    elif [[ -n ${dirs[$1]+_} ]]; then
        echo "Entering ${dirs[$1]}"
        cd ${dirs[$1]}
    else
        echo "No config for $1!"
    fi
}

# Clear link
cleardotlinks() {
    for ((i=2; i<=${#LLZDOTPAIRS[@]}; i+=2)); do
        [[ -L ${LLZDOTPAIRS[$i]} ]] && rm ${LLZDOTPAIRS[$i]}
    done
    if [[ -n $rimeloc ]]; then
        for f in "$LLZCFG/rime"/*; do
            local target="$rimeloc/$(basename $f)"
            [[ -L $target ]] && rm $target
        done
    fi
}

# }}}
# ZSH {{{

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes for a list of themes
# ZSH_THEME="candy"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Use case-insensitive completion
CASE_SENSITIVE="false"

# Use hyphen-insensitive completion. Treat _ and - interchangeably.
HYPHEN_INSENSITIVE="true"

# Just remind me to update when it's time
zstyle ':omz:update' mode reminder

# Trigger auto-update every 13 days
zstyle ':omz:update' frequency 13

# Disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# Enable command auto-correction.
ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Mark untracked files under VCS as dirty,
# at the expense of repo status check speed.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Manage the command execution time stamp shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(
    conda
    conda-zsh-completion
    copybuffer
    copyfile
    copypath
    git
    history
    macos
    python
    web-search
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# Individual descs:
# conda: provide aliases for conda commands themselves
# conda-zsh-completion: Complete conda command arguments
# copybuffer: Ctrl + O to copy command line buffer to clipboard
# copyfile: `copyfile` to copy a file to clipboard
# copypath: `copypath` to copy current directory path
# git: autocompletions with git commands
# history: `h` to show history, `hs` to grep history
# macos: `cdf` to cd to current Finder location, `rmdsstore` to remove dsstore
# python: `py` for python, `pyclean` to clean dummy files
# web-search `google milan` to google search milan
# zsh-syntax-highlighting: provides highlighting when on command line
# zsh-autosuggestions: auto-suggest zsh commands on command line

# TODO: Some things to consider in the future:
# ChrisPenner/copy-pasta: use copy and paste like in GUI

# AUTO-SUGGEST STRATGEGY
# completion: Chooses a suggestion based on what tab-completion would suggest.
#     (requires zpty module)
# match_prev_cmd: Like history, but chooses the most recent match whose
#     preceding history item matches the most recently executed command
# history: Chooses the most recent match from history.
ZSH_AUTOSUGGEST_STRATEGY=(completion history match_prev_cmd)

# Rest of oh-my-zsh
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# }}}
# GENERAL {{{

# Get current system name
sysname() {
    case $(uname -a) in
        *googler*)
            echo "gLinx"
            ;;
        *Ubuntu*)
            echo "Ubntu"
            ;;
        *Darwin*)
            echo "macOS"
            ;;
        *Linux*)
            echo "Linux"
            ;;
        *)
            echo "admin"
    esac
}

# Add this device key to ssh-agent so it can be forwarded to remotes
ssh-add ~/.ssh/cterdam &> /dev/null

# Make SSH ctrl path dir
mkdir -p ~/.ssh/ctrl

# Use conda python and pip instead of any system-installed versions
alias python3="python"
alias pip3="pip"

# Aliases for python and ipython
alias py="python"
alias ipy="ipython"

# Clear thoroughly
alias clear="clear && clear"

# Show Chinese characters; Do not show pycache
alias tree="tree -N -I '__pycache__'"

# Edit anything with neovim
alias nv="nvim"
export EDITOR="nvim"

# Use vim key bindings on cmdline
bindkey -v

# Do actual work here
cd $LLZHOME

# Alias for ls
alias l="ls"

# Use gruvbox theme for bat
export BAT_THEME="gruvbox-dark"

# Use bat to view man pages
if [[ `sysname` == "macOS" ]]; then
    export MANPAGER="bat -p"
else
    export MANPAGER="bat -l man -p"
fi

# Load Node Version Manager (NVM) if found
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Fix ruby versioning issues for Jekyll
if [[ $(sysname) == "macOS" ]]; then

    # These commands are managed by the brew installation of chruby

    # Use chruby to manage alternative Ruby versions
    source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
    # Enable auto-switching of Rubies specified by .ruby-version files
    source $(brew --prefix)/opt/chruby/share/chruby/auto.sh

    # Configure ruby version for Jekyll for Github Pages
    chruby ruby-3.4.1

else

    export GEM_HOME="$HOME/gems"
    addpath $HOME/gems/bin tail

fi

# }}}
# PATH {{{

# Prints each dir from PATH on its own line
# (assumes no ':' in directory names)
alias showpath='echo $PATH | tr ":" "\n"'

# Returns true iff argument in PATH
inpath() {
    [[ :$PATH: == *:$1:* ]]
}

# Adds something to PATH, head or tail
addpath() {
    case $2 in
        head) export PATH="$1:$PATH" ;;
        tail) export PATH="$PATH:$1" ;;
        "")   echo "Usage: addpath TARGET [head|tail]" ;;
        *)    echo "Unknown option: $2" ;;
    esac
}

# Deletes something from PATH, if present
delpath() {
    case $2 in
        first) export PATH=$(echo :$PATH | sed "s%:$1%%" | sed "s%^:%%g") ;;
        all)   export PATH=$(echo :$PATH | sed "s%:$1%%g" | sed "s%^:%%g") ;;
        "")    echo "Usage: delpath TARGET [first|all]" ;;
        *)     echo "Unknown option: $2" ;;
    esac
}

# Prepend pip install path
inpath ~/.local/bin || addpath ~/.local/bin head

# Add rust path
[[ -f $HOME/.cargo/env ]] && source $HOME/.cargo/env
inpath $HOME/.cargo/bin || addpath $HOME/.cargo/bin head

# }}}
# CONDA {{{

if [[ -d $HOME/opt/anaconda3 ]]; then
    condahomeloc=$HOME/opt/anaconda3
elif [[ -d /opt/anaconda3 ]]; then
    condahomeloc=/opt/anaconda3
elif [[ -d $HOME/anaconda3 ]]; then
    condahomeloc=$HOME/anaconda3
elif [[ -d $HOME/opt/miniconda3 ]]; then
    condahomeloc=$HOME/opt/miniconda3
elif [[ -d /opt/miniconda3 ]]; then
    condahomeloc=/opt/miniconda3
elif [[ -d $HOME/miniconda3 ]]; then
    condahomeloc=$HOME/miniconda3
elif [[ -f /usr/local/bin/conda ]]; then
    condahomeloc=/usr/local
else
    echo "Warning: conda installation not found, skipping." >&2
    condahomeloc=""
fi

# >>> conda initialize >>>
if [[ -n $condahomeloc ]]; then
    condaloc=$condahomeloc/bin/conda
    __conda_setup="$($condaloc 'shell.zsh' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "$condahomeloc/etc/profile.d/conda.sh" ]; then
            . "$condahomeloc/etc/profile.d/conda.sh"
        else
            addpath "$condahomeloc/bin" head
        fi
    fi
    unset __conda_setup
fi
# <<< conda initialize <<<

alias cerm='conda env remove -n'

# }}}
# GIT {{{

# Function to view git diff with bat
batdiff() {
    command git diff --name-only --diff-filter=d $@ | xargs bat --diff
}

# Command to view the root of this git repo
alias gitroot='git rev-parse --show-toplevel'

# Command to view git logline
alias gll='git logline'

# }}}
# {{{ AUTO

# Automatically run function when changing directory
function change_dir_auto() {

    # Run in zsh-compatible local mode
    emulate -L zsh

    # Auto ls
    ls

    # If in tmux, force redraw status line
    if [[ -n "$TMUX" ]]; then
        tmux refresh-client -S
    fi

}
if [[ ${chpwd_functions[(r)change_dir_auto]} != "change_dir_auto" ]]; then
  chpwd_functions+=("change_dir_auto")
fi

# }}}
# LLZBIN {{{

# dir to hold executables
export LLZBIN="$LLZHOME/bin"
mkdir -p $LLZBIN
inpath $LLZBIN || addpath $LLZBIN head

# Prioritize homebrew vi over default
homebrewbinloc="/opt/homebrew/bin"
if [[ -d $homebrewbinloc ]]; then
    for homebrewvimbin in $homebrewbinloc/(*vim*|vi); do
        linkfile "$homebrewvimbin" "$LLZBIN/$(basename $homebrewvimbin)"
    done
fi

# Add exe from cfg
for exefile in "$LLZHOME/cfg/exe"/*; do
    chmod 755 $exefile
    linkfile "$exefile" "$LLZBIN/$(basename $exefile)"
done

# Fix issue where bat goes by batcat on some Linux systems
if [[ ! "$(command -v bat)" && "$(command -v batcat)" ]]; then
    linkfile "$(which batcat)" "$LLZBIN/bat"
fi

# }}}
# TMUX {{{

# Pick correct tmux command name
if [ $(sysname) = "gLinx" ]; then
    # Use tmx2 as tmux command name on gLinux
    tmuxname=tmx2
    # Use tmux completion for tmx2
    compdef tmx2=tmux
else
    tmuxname=tmux
fi

# Start tmux session if not running
if [[ -z "$TMUX" ]]; then
    $tmuxname new-session -A -s $(sysname)
fi

# Make tmux refresh every second
# The same setting in tmux.conf doesn't seem to work
tmux set-option -g status-interval 1

# }}}
# GOOGLE {{{

if [ $(sysname) = "gLinx" ]; then

    # Use hgd
    source /etc/bash_completion.d/hgd

    # Load GDM common bashrc
    if [ -r /google/data/ro/teams/deepmind-eng/config/bashrc ] ; then
        source /google/data/ro/teams/deepmind-eng/config/bashrc
    fi
    # Load XManager bashrc
    if [ -r /google/data/ro/teams/dmgi/configs/google_xm_bashrc ] ; then
        source /google/data/ro/teams/dmgi/configs/google_xm_bashrc
    fi
    # Load Adbrain bashrc
    if [ -r /usr/share/adbrain/adbrain.sh ] ; then
        . /usr/share/adbrain/adbrain.sh
    fi

    # path shortcuts
    alias sa="cd learning/deepmind/incubation/applied_language/conv_ai/supportassist"
    alias gemax="cd learning/gemini/gemax/experimental/supportassist"
    alias gt="cd gdm/ads/geminitagger"
    alias exp="cd experimental/users/cterdam"

    # program shortcuts
    alias aclcheck='/google/bin/releases/ganpati-acls/tools/aclcheck'
    alias bkill='/google/data/ro/teams/borgtools/bkill'
    alias clhead='readlink /google/src/files/head'
    alias colab="/google/bin/releases/grp-ix-team/rapid/colab-cli/cli.par"
    alias er='/google/data/ro/users/ho/hooper/er'
    alias gemini='/google/bin/releases/gemini-cli/tools/gemini'
    alias hm='/google/bin/releases/heinzelmaennchen-team-policy/cli/hm'
    alias legoml='/google/data/ro/teams/legoml/legoml'
    alias securemymodel='/google/bin/releases/airr-saif-data/securemymodel/securemymodel'

    # hg aliases
    alias hgs='hg status'
    alias hgl='hg citc -l'
    alias hga='hg add'
    alias hgc='hg commit'
    alias hgm='hg amend'
    alias hgmu='hg amend && hg ut'
    alias hguc='hg uc'
    alias hgut='hg ut'
    alias hgxl='hg xl'
    alias hgdf='hg diff'
    alias hgeu='hg evolve && hg ut'

    # Prepend CTERDAMBIN
    jetski_path="/Users/cterdam/.jetski/jetski/bin"
    if ! inpath $jetski_path; then
        addpath $jetski_path tail
    fi

    # Fig integration -----------------------------------------------------------------
    # go/zsh-prompt#zsh-fig-prompt-fig-status-fig-prompt-and-powerlevel10k-custom-segment

    ### Fig prompt file

    # Fig prompt file on google3
    figpromptsource=/google/src/files/head/depot/google3/experimental/fig_contrib/prompts/fig_status/zsh/fig_prompt

    # Location for fig prompt
    figpromptloc="$HOME/.figprompt"

    # Copy, if not already present
    if [[ -f $figpromptsource && ! -f $figpromptloc ]]; then
        cp $figpromptsource $figpromptloc
    fi

    # Source the fig prompt file
    source $figpromptloc

    ### Fig status file

    # Fig status file on google3
    figstatussource=/google/src/head/depot/google3/experimental/fig_contrib/prompts/fig_status/fig_status.py

    # Location for fig prompt
    figstatusloc="$HOME/.figstatus"

    # Copy, if not already present
    if [[ -f $figstatussource && ! -f $figstatusloc ]]; then
        cp $figstatussource $figstatusloc
    fi

    # Template Arguments:
    #   FIG_PROMPT_MODIFIED: Replaced with $modified
    #   FIG_PROMPT_ADDED: Replaced with $added
    #   FIG_PROMPT_DELETED: Replaced with $deleted
    #   FIG_PROMPT_UNKNOWN: Replaced with $unknown
    #   FIG_PROMPT_UNEXPORTED: Replaced with $unexported
    #   FIG_PROMPT_OBSOLETE: Replaced with $obsolete
    #   FIG_PROMPT_CL: Replaced with $cl
    #   FIG_PROMPT_DESCRIPTION: Replaced with $description
    #   FIG_PROMPT_CHANGENAME: Replaced with $changename
    #   FIG_PROMPT_HAS_SHELVE: Replaced with $has_shelve
    function get_fig_prompt_template() {
        echo -n '%F{black}FIG_PROMPT_ADDED'
        echo -n '%F{black}FIG_PROMPT_MODIFIED'
        echo -n '%F{black}FIG_PROMPT_DELETED'
        echo -n '%F{black}FIG_PROMPT_UNKNOWN'
        echo -n '%F{black}FIG_PROMPT_HAS_SHELVE'
        echo -n '%F{black}FIG_PROMPT_UNEXPORTED'
        echo -n '%F{black}FIG_PROMPT_OBSOLETE'
        echo -n '  %F{black}FIG_PROMPT_DESCRIPTION'
        echo -n ' %F{240}FIG_PROMPT_CL'
    }

    # Custom p10k segment for fig
    # Will only appear when the directory is a citc client
    function prompt_fig() {
        local fig_prompt
        fig_prompt="$(get_fig_prompt)"
        p10k segment -f 208 -c $fig_prompt -t $fig_prompt
    }

    # Add support for Snap (go/snap-cl) and enable it by default. #!>>SNAP<<!#
    if [[ -r /google/data/ro/teams/ix-ml/snap/config/bashrc ]] ; then #!>>SNAP<<!#
      source /google/data/ro/teams/ix-ml/snap/config/bashrc #!>>SNAP<<!#
    fi #!>>SNAP<<!#
    export SNAP_DEFAULT_FOR_SYNC=true #!>>SNAP<<!#
    export SNAP_DEFAULT_FOR_NEW_WORKSPACE=true #!>>SNAP<<!#

    # Utility to rename citc workspace
    function citc_rename() {
        if [ $# -ne 2 ]; then
            echo "Usage: citc_rename <oldname> <newname>"
            return 1
        fi

        local old_name="$1"
        local new_name="$2"
        local current_dir=$(pwd)
        local workspace_root="/google/src/cloud/$USER/${old_name}"

        # Check if the current directory is within the workspace being renamed
        if [[ "${current_dir}" == "${workspace_root}"* ]]; then
            echo "ERROR: You cannot run this script from within the workspace you are trying to rename."
            echo "Please change your current directory outside of '${workspace_root}' and try again."
            return 1
        fi

        local delete_output
        local ws_num

        delete_output=$(hg citc -d "${old_name}")
        if [ $? -ne 0 ]; then
            echo "Failed to delete workspace ${old_name}"
            return 1
        fi

        echo "${delete_output}"
        ws_num=$(echo "${delete_output}" | awk '/--undelete/ {print $(NF)}')

        if [ -z "${ws_num}" ]; then
            echo "Could not extract workspace number from hg output."
            return 1
        fi

        hg citc "${new_name}" --undelete "${ws_num}"
        if [ $? -ne 0 ]; then
            echo "Failed to undelete workspace as ${new_name}"
            # Attempt to restore the old workspace
            echo "Attempting to restore ${old_name}..."
            hg citc "${old_name}" --undelete "${ws_num}"
            return 1
        fi

        echo "Successfully renamed workspace '${old_name}' to '${new_name}'"
    }

fi

# }}}
