#!/bin/bash

tmux rename-window clp

# Connect to the tmux session already running on the server.
gcertstatus -nocheck_ssh -check_remaining=1h || gcert
ssh clp -t -- /bin/bash -c "gcertstatus -nocheck_ssh -check_remaining=1h || gcert; tmx2 new-session -A -s gLinx"
