#!/usr/bin/expect -f

set source [lindex $argv 0]

spawn scp osrdr:$source $env(HOME)/Desktop

expect "liangzli@100.109.20.38's password: "
send $env(OCI_PW)
send "\n"

expect "liangzli@osrdr-proj-mlrg-language-models02's password: "
send $env(OCI_PW)
send "\n"

interact
